#docker-composeのver指定
version: "3.4"
services:
  app: 
    container_name: python_app
    build:

      #認識する範囲
      context: .

      #Dockerfileからbuild
      dockerfile: ./Dockerfile
  db:
    #dockerhubからpullするイメージ
    image: mysql:5.7.37
    container_name: mysql_db

    #環境変数をコンテナに渡す
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db 
    ports:
      - 3306:3306